export const API = {
    ADMIN:{
        SIGNIN:"/admin/signin",
        LOGOUT:"/admin/logout",
        LEARNERS:"/admin/learners",
        INSTRUCTORS:"/admin/instructors",
        BUSINESSES:"/admin/businesses",
        LEARNER_STATUS:"/admin/learner/status",
        INSTRUCTOR_STATUS:"/admin/instructor/status",
        BUSINESS_STATUS:"/admin/business/status",
        INSTRUCTOR_VERIFICATION:"/admin/instructor/verification",
        BUSINESS_VERIFICATION:"admin/business/verification",
        CATEGORY:"/admin/category",
        CATEGORIES:"/admin/categories",
        STATUS:"/admin/category/status",
        COURSES:"/admin/courses"

    },
    AUTH: {
        SIGNUP: "/auth/signup",
        SIGNIN: "/auth/signin",
        LOGOUT: "/auth/logout",
        REFRESH: "/auth/refresh",
        RESEND_OTP: "/auth/otp/resend",
        VERIFY_OTP: "/auth/otp/send",
        GOOGLE_SIGNIN:"/auth/google",
        VERIFY_EMAIL:'/auth/reset/email',
        VERIFY_RESET_OTP:'/auth/reset/otp',
        RESET_PASSWORD:'/auth/reset'
    },
    LEARNER: {
        DASHBOARD: "/learner/dashboard",
        PROFILE: "/learner/profile",
        COURSES: "/learner/courses",
        PROFILE_IMAGE:`/learner/profile/image`,
        PASSWORD:`/learner/password`,
    },
    INSTRUCTOR: {
        DASHBOARD: "/instructor/dashboard",
        COURSES: "/instructor/courses",
        PROFILE:`/instructor/profile`,
        PROFILE_IMAGE:`/instructor/profile/image`,
        RESUME:`/instructor/profile/resume`,
        ID_PROOF:`/instructor/profile/identity-proof`,
        EXPERTISE:`/instructor/profile/expertise`,
        PASSWORD:`/instructor/password`,
        VERIFICATION:`/instructor/verification`,
        COURSE:"/instructor/course",
        CATEGORIES:"/instructor/categories",
        COURSE_INFO:"/instructor/course/info",
        COURSE_THUMBNAIL:"/instructor/course/thumbnail",
        COURSE_PREVIEW_VIDEO:"/instructor/course/preview-video",
        COURSE_OBJECTIVES:"/instructor/course/objectives",
        COURSE_TAGS:"/instructor/course/tags",
        COURSE_PREREQUISITES:"instructor/course/prerequisites",
        ADD_MODULE:"/instructor/course/module/add",
        ADD_CHAPTER:"/instructor/course/chapter/add",
        UPDATE_MODULE:"/instructor/course/module/update"
    },
    BUSINESS: {
        DASHBOARD: "/business/dashboard",
        EMPLOYEES: "/business/employees",
        PLANS: "/business/plans",
        PROFILE:`/business/profile`,
        PROFILE_IMAGE:`/business/profile/image`,
        LICENSE:`/business/profile/license`,
        PASSWORD:`/business/password`,
        VERIFICATION:`/business/verification`
    },

} as const;
