
export const API = {
    ADMIN:{
        SIGNIN:"/admin/signin",
        LOGOUT:"/admin/logout",
        LEARNERS:"/admin/learners",
        INSTRUCTORS:"/admin/instructors",
        BUSINESSES:"/admin/businesses",
        LEARNER_STATUS:"/admin/learner/status",
        INSTRUCTOR_STATUS:"/admin/instructor/status",
        BUSINESS_STATUS:"/admin/business/status",
        INSTRUCTOR_VERIFICATION:"/admin/instructor/verification",
        BUSINESS_VERIFICATION:"admin/business/verification",
        CATEGORY:"/admin/category",
        CATEGORIES:"/admin/categories",
        STATUS:"/admin/category/status",
        COURSES:"/admin/courses",
        COURSE:"/admin/course",
        COURSE_VERIFICATION:"/admin/course/verification",
        COURSE_ANALYTICS:"/admin/course/analytics",
        COUPON:"/admin/coupon",
        COUPONS:"/admin/coupons",
        COUPON_STATUS:"/admin/coupon/status",
        DASHBOARD:"/admin/dashboard",



    },
    AUTH: {
        SIGNUP: "/auth/signup",
        SIGNIN: "/auth/signin",
        LOGOUT: "/auth/logout",
        REFRESH: "/auth/refresh",
        RESEND_OTP: "/auth/otp/resend",
        VERIFY_OTP: "/auth/otp/send",
        GOOGLE_SIGNIN:"/auth/google",
        VERIFY_EMAIL:'/auth/reset/email',
        VERIFY_RESET_OTP:'/auth/reset/otp',
        RESET_PASSWORD:'/auth/reset'
    },
    LEARNER: {
        DASHBOARD: "/learner/dashboard",
        PROFILE: "/learner/profile",
        COURSES: "/learner/courses",
        PROFILE_IMAGE:`/learner/profile/image`,
        PASSWORD:`/learner/password`,
        COURSE_PREVIEW:"/learner/course/preview",
        CHECKOUT:"/learner/course/checkout",
        INITIATE_PAYMENT:"/payment/initiate",
        VERIFY_PAYMENT:"/payment/verify",
        ENROLLMENTS:"/learner/enrollments",
        LEARN_COURSE:"/learner/course/learn",
        CHAPTER_COMPLETE:"learner/progress/chapter/complete",
        FAVOURITES:"/learner/favourites",
        CONVERSATIONS:"/learner/conversations",
        QUIZ:"/learner/quiz",
        CERTIFICATES:"/learner/certificates",
        MESSAGES:"/learner/messages",
        COURSE_VIDEO:"/learner/video",
        PING:"/learner/ping",
        CURRENT_CHAPTER:"/learner/progress/chapter/current",
        DELETE_MESSAGE:"/learner/messages/delete",
        JOIN_SESSION:"/learner/session/join",
        SESSIONS:"/learner/sessions",
        REVIEW:"/learner/course/review",
        REVIEWS:"/learner/course/reviews",
        HOME:"/learner/home",
        HOME_LEARNER_DATA:"/learner/home/learner-data",
        POPULAR_COURSES:"/learner/courses/popular",
        CANCEL_ENROLLMENT:"/learner/enrollment/cancel",
        WALLET:"/learner/wallet"



    },
    INSTRUCTOR: {
        DASHBOARD: "/instructor/dashboard",
        COURSES: "/instructor/courses",
        PROFILE:`/instructor/profile`,
        PROFILE_IMAGE:`/instructor/profile/image`,
        RESUME:`/instructor/profile/resume`,
        ID_PROOF:`/instructor/profile/identity-proof`,
        EXPERTISE:`/instructor/profile/expertise`,
        PASSWORD:`/instructor/password`,
        VERIFICATION:`/instructor/verification`,
        COURSE:"/instructor/course",
        CATEGORIES:"/instructor/categories",
        COURSE_INFO:"/instructor/course/info",
        COURSE_THUMBNAIL:"/instructor/course/thumbnail",
        COURSE_PREVIEW_VIDEO:"/instructor/course/preview-video",
        COURSE_OBJECTIVES:"/instructor/course/objectives",
        COURSE_TAGS:"/instructor/course/tags",
        COURSE_PREREQUISITES:"instructor/course/prerequisites",
        ADD_MODULE:"/instructor/course/module/add",
        ADD_CHAPTER:"/instructor/course/chapter/add",
        UPDATE_MODULE:"/instructor/course/module/update",
        DELETE_MODULE:"/instructor/course/module/delete",
        UPDATE_CHAPTER_INFO:"/instructor/course/chapter/update",
        UPDATE_VIDEO:"/instructor/course/video/update",
        DELETE_CHAPTER:"/instructor/course/chapter/delete",
        COURSE_VERIFICATION:"/instructor/course/verification",
        UPDATE_COURSE_STATUS:"/instructor/course/status",
        ADD_RESOURCE:"/instructor/course/resource/add",
        DELETE_RESOURCE:"/instructor/course/resource/delete",
        QUIZ:"/instructor/course/quiz",
        QUIZ_QUESTION:"/instructor/course/quiz/question",
        CONVERSATIONS:"/instructor/conversations",
        MESSAGES:"/instructor/messages",
        DELETE_MESSAGES:"/instructor/messages/delete",
        COURSE_OPTIONS:"/instructor/course/options",
        SESSION:"/instructor/session",
        SESSIONS:"/instructor/sessions",
        START_SESSION:"/instructor/session/start",
        END_SESSION:"/instructor/session/end",
        CANCEL_SESSION:"/instructor/session/cancel",
        EARNINGS:"/instructor/earnings",
        COURSE_ANALYTICS:"/instructor/course/analytics",
        LEARNERS:"/instructor/learners"


    },
    BUSINESS: {
        DASHBOARD: "/business/dashboard",
        EMPLOYEES: "/business/employees",
        PLANS: "/business/plans",
        PROFILE:`/business/profile`,
        PROFILE_IMAGE:`/business/profile/image`,
        LICENSE:`/business/profile/license`,
        PASSWORD:`/business/password`,
        VERIFICATION:`/business/verification`
    },

} as const;
